// Enhanced mock data for fallback when session storage is empty
export const mockNgoAppsData = [
  {
    id: "mock_001",
    userType: "ngo",
    name: "DriveX - Business Plan",
    organizationName: "DriveX - Business Plan",
    email: "bpxailabs@gmail.com",
    password: "",
    description:
      "Building innovative solutions for sustainable transportation and environmental impact reduction.",
    website: "https://www.drivex.com",
    category: "environment",
    agreeTerms: true,
    registrationNumber: "REG-2024-DRX-001",
    foundedYear: "2023",
    teamSize: "15-25",
    twitter: "https://twitter.com/drivex",
    facebook: "https://facebook.com/drivex",
    linkedin: "https://linkedin.com/company/drivex",
    walletAddress: "0xdf744ba5808cde3e87b3390a8a3dce5ccb349068",
    status: "pending",
    submittedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    contactPerson: "Koleen BP",
    phone: "+1-555-0123",
  },
  {
    id: "mock_002",
    userType: "ngo",
    name: "Green Future Initiative",
    organizationName: "Green Future Initiative",
    email: "contact@greenfuture.org",
    description:
      "Dedicated to environmental conservation, renewable energy advocacy, and climate change education in urban communities.",
    website: "https://www.greenfuture.org",
    category: "environment",
    agreeTerms: true,
    registrationNumber: "REG-2024-GFI-002",
    foundedYear: "2022",
    teamSize: "25-50",
    twitter: "https://twitter.com/greenfuture",
    facebook: "https://facebook.com/greenfutureorg",
    linkedin: "https://linkedin.com/company/greenfuture",
    walletAddress: "0x8ba1f109551bD432803012645Hac136c30C6213",
    status: "under_review",
    submittedAt: new Date(Date.now() - 86400000).toISOString(), // 1 day ago
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    contactPerson: "Koleen BP",
    phone: "+1-555-0456",
  },
  {
    id: "mock_003",
    userType: "ngo",
    name: "Education Access Foundation",
    organizationName: "Education Access Foundation",
    email: "info@educationaccess.org",
    description:
      "Providing educational resources and opportunities to underserved communities worldwide through technology and mentorship programs.",
    website: "https://www.educationaccess.org",
    category: "education",
    agreeTerms: true,
    registrationNumber: "REG-2024-EAF-003",
    foundedYear: "2021",
    teamSize: "50-100",
    twitter: "https://twitter.com/educationaccess",
    facebook: "https://facebook.com/educationaccessfdn",
    linkedin: "https://linkedin.com/company/educationaccess",
    walletAddress: "0x742d35Cc6634C0532925a3b8D4C0C8b3C2e1e416",
    status: "approved",
    submittedAt: new Date(Date.now() - 172800000).toISOString(), // 2 days ago
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    reviewedAt: new Date(Date.now() - 86400000).toISOString(),
    reviewedBy: "admin@don8.com",
    reviewNotes:
      "Excellent documentation and clear mission statement. Approved for platform access.",
    contactPerson: "Arya Stark",
    phone: "+1-555-0789",
  },
];
